apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: workspace-protection-binding
spec:
  policyName: workspace-protection
  validationActions: [Deny]
  matchResources: {}
