# This rule is not used by the project otterscale-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to addons.otterscale.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: otterscale-operator
    app.kubernetes.io/managed-by: kustomize
  name: addons-moduletemplate-viewer-role
rules:
- apiGroups:
  - addons.otterscale.io
  resources:
  - moduletemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.otterscale.io
  resources:
  - moduletemplates/status
  verbs:
  - get
