# This rule is not used by the project otterscale-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over core.otterscale.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: otterscale-operator
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: workspace-admin-role
rules:
  - apiGroups:
      - core.otterscale.io
    resources:
      - workspaces
    verbs:
      - "*"
  - apiGroups:
      - core.otterscale.io
    resources:
      - workspaces/status
    verbs:
      - get
