apiVersion: addons.otterscale.io/v1alpha1
kind: Module
metadata:
  labels:
    app.kubernetes.io/name: otterscale-operator
    app.kubernetes.io/managed-by: kustomize
  name: module-sample
spec:
  # TODO(user): Add fields here
