apiVersion: core.otterscale.io/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: otterscale-operator
    app.kubernetes.io/managed-by: kustomize
  name: workspace-sample
spec:
  # TODO(user): Add fields here
