apiVersion: tenant.otterscale.io/v1alpha1
kind: Workspace
metadata:
  labels:
    app.kubernetes.io/name: otterscale-operator
    app.kubernetes.io/managed-by: kustomize
  name: workspace-sample
spec:
  namespace: "this-is-user-namespace"
  users:
    - name: "aaa"
      subject: "aaa"
      role: "admin"
    - name: "bbb"
      subject: "bbb"
      role: "edit"
    - name: "ccc"
      subject: "ccc"
      role: "view"
  resourceQuota:
    hard:
      requests.cpu: "1"
      requests.memory: "1Gi"
      limits.cpu: "2"
      limits.memory: "2Gi"
      requests.nvidia.com/gpu: 4
  limitRange:
    limits:
      - default:
          cpu: 500m
        defaultRequest:
          cpu: 500m
        max:
          cpu: "1"
        min:
          cpu: 100m
        type: Container
  networkIsolation:
    enabled: true
    allowedNamespaces: ["kube-system", "otterscale-operator-system"]
